=== Taiizor/Store/src/SucroseInfoSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Sucrose Wallpaper Info Schema",
  "description": "JSON schema for defining wallpaper app information.",
  "type": "object",
  "properties": {
    "AppVersion": { "type": "string", "description": "Version of the app." },
    "Version": { "type": "string", "description": "Version of the wallpaper." },
    "Title": { "type": "string", "description": "Title of the wallpaper.", "maxLength": 50 },
    "Thumbnail": { "type": "string", "description": "Thumbnail image of the wallpaper." },
    "Preview": { "type": "string", "description": "Preview image or animation of the wallpaper." },
    "Description": { "type": "string", "description": "Description of the wallpaper.", "maxLength": 500 },
    "Author": { "type": "string", "description": "Author of the wallpaper.", "maxLength": 50 },
    "License": { "type": ["string", "null"], "description": "License information for the wallpaper (string or null)." },
    "Contact": { "type": "string", "description": "Contact information for the wallpaper.", "maxLength": 250 },
    "Type": { "type": "integer", "description": "Type of the wallpaper." },
    "Source": { "type": "string", "description": "Source location of the wallpaper." },
    "Tags": { "type": ["array", "null"], "items": { "type": "string" }, "minItems": 1, "maxItems": 10, "description": "Tags associated with the wallpaper (array or null)." },
    "Arguments": { "type": ["string", "null"], "description": "Arguments for the wallpaper (string or null).", "maxLength": 250 }
  },
  "required": ["AppVersion", "Version", "Title", "Thumbnail", "Preview", "Description", "Author", "License", "Contact", "Type", "Source", "Tags", "Arguments"],
  "additionalProperties": false
}

=== Taiizor/Store/src/Landscape/Summer Meteor-1/SucroseInfo.json
{
  "AppVersion": "24.7.23.0",
  "Version": "1.0.0.0",
  "Title": "Summer Meteor",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Summer Meteor - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/summer-meteor",
  "Type": 3,
  "Source": "sm.mp4",
  "Tags": [
    "Shooting Star",
    "Skywatching",
    "Stargazing",
    "Astronomy",
    "Night Sky"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Brands/Neon Sign-1/SucroseInfo.json
{
  "AppVersion": "24.9.21.0",
  "Version": "1.0.0.1",
  "Title": "Neon Sign",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Neon Sign - Coca Cola - Live Wallpaper",
  "Author": "MoeWalls",
  "License": null,
  "Contact": "https://moewalls.com/abstract/coca-cola-neon-sign-live-wallpaper",
  "Type": 3,
  "Source": "ccns.mp4",
  "Tags": [
    "Logo"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Lifestyle/Anime Street View-1/SucroseInfo.json
{
  "AppVersion": "24.8.8.0",
  "Version": "1.0.0.0",
  "Title": "Anime Street View",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Anime Street View - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/anime-street",
  "Type": 3,
  "Source": "asv.mp4",
  "Tags": [
    "Brustling",
    "Immersive",
    "Vibrant",
    "Lively",
    "Urban"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Black and White/Driving Under The Moonlight In The Forest-1/SucroseInfo.json
{
  "AppVersion": "24.8.7.0",
  "Version": "1.0.0.0",
  "Title": "Driving Under The Moonlight In The Forest",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Driving Under The Moonlight In The Forest - Live Wallpaper",
  "Author": "MoeWalls",
  "License": null,
  "Contact": "https://moewalls.com/landscape/driving-under-the-moonlight-in-the-forest-live-wallpaper",
  "Type": 3,
  "Source": "dutmitf.mp4",
  "Tags": [
    "Moonlit Night",
    "Shooting Star",
    "Trees",
    "Car"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Game/Ellie-5/SucroseInfo.json
{
  "AppVersion": "24.7.12.0",
  "Version": "1.0.0.0",
  "Title": "Ellie",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Ellie - The Last Of Us Part II - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/Live-Wallpaper-The-Last-of-Us-2-",
  "Type": 3,
  "Source": "etloupii.mp4",
  "Tags": [
    "Ellie Williams"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Anime/Zoro Sword Fight-1/SucroseInfo.json
{
  "AppVersion": "24.9.21.0",
  "Version": "1.0.0.0",
  "Title": "Zoro Sword Fight",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Zoro Sword Fight - One Piece - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/zoro-sword-fight",
  "Type": 3,
  "Source": "zsfop.mp4",
  "Tags": [
    "Determined",
    "Swordsman",
    "Samurai",
    "Skilled",
    "Vibrant"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Vehicles/Ferrari 458 Italia-1/SucroseInfo.json
{
  "AppVersion": "24.7.1.0",
  "Version": "1.0.0.1",
  "Title": "Ferrari 458 Italia",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Ferrari 458 Italia - Need For Speed - Live Wallpaper",
  "Author": "MoeWalls",
  "License": null,
  "Contact": "https://moewalls.com/vehicle/ferrari-458-italia-need-for-speed-live-wallpaper",
  "Type": 3,
  "Source": "f458infs.mp4",
  "Tags": [
    "Raining",
    "Night"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Film and TV/Petyr Baelish-1/SucroseInfo.json
{
  "AppVersion": "24.7.7.0",
  "Version": "1.0.0.0",
  "Title": "Petyr Baelish",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Petyr Baelish - Game of Thrones - Live Wallpaper",
  "Author": "MoeWalls",
  "License": null,
  "Contact": "https://moewalls.com/movies/petyr-baelish-game-of-thrones-live-wallpaper",
  "Type": 3,
  "Source": "pbgot.mp4",
  "Tags": [
    "Explosion",
    "Frozen",
    "Winter",
    "Cloak",
    "Cape"
  ],
  "Arguments": null
}
