=== Taiizor/Store/src/SucroseInfoSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Sucrose Wallpaper Info Schema",
  "description": "JSON schema for defining wallpaper app information.",
  "type": "object",
  "properties": {
    "AppVersion": { "type": "string", "description": "Version of the app." },
    "Version": { "type": "string", "description": "Version of the wallpaper." },
    "Title": { "type": "string", "description": "Title of the wallpaper.", "maxLength": 50 },
    "Thumbnail": { "type": "string", "description": "Thumbnail image of the wallpaper." },
    "Preview": { "type": "string", "description": "Preview image or animation of the wallpaper." },
    "Description": { "type": "string", "description": "Description of the wallpaper.", "maxLength": 500 },
    "Author": { "type": "string", "description": "Author of the wallpaper.", "maxLength": 50 },
    "License": { "type": ["string", "null"], "description": "License information for the wallpaper (string or null)." },
    "Contact": { "type": "string", "description": "Contact information for the wallpaper.", "maxLength": 250 },
    "Type": { "type": "integer", "description": "Type of the wallpaper." },
    "Source": { "type": "string", "description": "Source location of the wallpaper." },
    "Tags": { "type": ["array", "null"], "items": { "type": "string" }, "minItems": 1, "maxItems": 10, "description": "Tags associated with the wallpaper (array or null)." },
    "Arguments": { "type": ["string", "null"], "description": "Arguments for the wallpaper (string or null).", "maxLength": 250 }
  },
  "required": ["AppVersion", "Version", "Title", "Thumbnail", "Preview", "Description", "Author", "License", "Contact", "Type", "Source", "Tags", "Arguments"],
  "additionalProperties": false
}

=== Taiizor/Store/src/Anime/Luffy One Piece Bird Friendship-1/SucroseInfo.json
{
  "AppVersion": "24.9.14.0",
  "Version": "1.0.0.0",
  "Title": "Luffy One Piece Bird Friendship",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Luffy One Piece Bird Friendship - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/luffy-one-piece-bird-friendship",
  "Type": 3,
  "Source": "lopbf.mp4",
  "Tags": [
    "Monkey D Luffy",
    "Manga"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Anime/Gojo Satoru Jujutsu Kaisen Grey-1/SucroseInfo.json
{
  "AppVersion": "24.9.21.0",
  "Version": "1.0.0.0",
  "Title": "Gojo Satoru Jujutsu Kaisen Grey",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Gojo Satoru Jujutsu Kaisen Grey - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/gojo-grey",
  "Type": 3,
  "Source": "gsjkg.mp4",
  "Tags": [
    "Cursed Energy",
    "Action Pose",
    "Anime Hero",
    "Grey Theme",
    "Sorcerer"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Anime/Sukuna God-1/SucroseInfo.json
{
  "AppVersion": "24.7.28.0",
  "Version": "1.0.0.0",
  "Title": "Sukuna God",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Sukuna God - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/sukuna-god",
  "Type": 3,
  "Source": "sg.mp4",
  "Tags": [
    "Jujutsu Kaisen",
    "Cursed Spirit",
    "Ryomen Sukuna",
    "Divine Being",
    "Manga"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Game/Yoimiya-1/SucroseInfo.json
{
  "AppVersion": "24.7.9.0",
  "Version": "1.0.0.0",
  "Title": "Yoimiya",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Yoimiya - Genshin Impact - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/Yoimiya-Genshin",
  "Type": 3,
  "Source": "ygi.mp4",
  "Tags": [
    "Bow User",
    "Fantasy",
    "Mihoyo",
    "Fire",
    "Pyro"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Anime/White Wattle Corridor-1/SucroseInfo.json
{
  "AppVersion": "24.8.8.0",
  "Version": "1.0.0.0",
  "Title": "White Wattle Corridor",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "White Wattle Corridor - Dark Alley - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/white-wattle-corridor",
  "Type": 3,
  "Source": "wwcda.mp4",
  "Tags": [
    "Moody Atmosphere",
    "Narrow Passage",
    "Dimly Lit",
    "Shadowy",
    "Eerie"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Anime/Zenitsu Agatsuma-2/SucroseInfo.json
{
  "AppVersion": "24.8.8.0",
  "Version": "1.0.0.0",
  "Title": "Zenitsu Agatsuma",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Zenitsu Agatsuma - Kimetsu no Yaiba - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/zenitsu-kimetsu_fKl",
  "Type": 3,
  "Source": "zakny.mp4",
  "Tags": [
    "Thunder Breathing",
    "Demon Slayer",
    "Yellow Hair",
    "Lightning",
    "Swordsman"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Anime/Arona and Plana-1/SucroseInfo.json
{
  "AppVersion": "24.7.28.0",
  "Version": "1.0.0.0",
  "Title": "Arona and Plana",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Arona and Plana - Blue Archive - Live Wallpaper",
  "Author": "MoeWalls",
  "License": null,
  "Contact": "https://moewalls.com/anime/arona-and-plana-blue-archive-live-wallpaper",
  "Type": 3,
  "Source": "aapba.mp4",
  "Tags": [
    "School Uniform",
    "Angel Ring",
    "Short Hair",
    "Blue Hair",
    "Whale"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Lifestyle/Old Town Rain-1/SucroseInfo.json
{
  "AppVersion": "24.7.13.0",
  "Version": "1.0.0.0",
  "Title": "Old Town Rain",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Old Town Rain - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/old-town-rain",
  "Type": 3,
  "Source": "otr.mp4",
  "Tags": [
    "Aesthetic",
    "Rainy Day",
    "Ambient",
    "Vintage",
    "Cozy"
  ],
  "Arguments": null
}
